<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SCN_001_Daftar - Data Tidak Valid</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>dc92cbf5-2003-40ab-9729-3a103f4f73a9</testSuiteGuid>
   <testCaseLink>
      <guid>631862e4-edae-4bc3-90b2-530b524007eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Daftar/SCN_001_TC_002_Daftar - First Name Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>382efbc4-f06c-46d9-84fc-0351f91664a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>850bba27-7112-4487-9854-45ea40a621e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3243691c-8a2b-472c-8298-b9e2b74cd594</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce359689-1b6a-4a64-a18e-8d7f9b67e331</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e4cfd4e-23c0-4bc0-87ce-399dd3aeb36e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d53e96e4-14fd-4361-8d4a-fa27d7eac333</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d51a62e-fa94-4fcd-b2c9-1517268ed8b0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8db81a05-7b52-4b38-96ae-0873c1dec6d8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Daftar/SCN_001_TC_003_Daftar - Last Name Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1343560-b2b8-4a8c-b935-4c3174edb8bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1ecbd26-9aff-4130-abd6-6c1a723d2e32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c86ca57-57c4-415f-8a9b-e479df802a20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7b6255c-58f4-4cf8-852f-ec4f490a8e5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>910f90f2-2772-438d-9558-9c48b0129684</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96c80630-3665-43a7-ba7b-6fed1d8979ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a00143c4-f6b4-4d91-aac3-12a6f8f8686c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>629238eb-3b8b-42dd-85ba-6c33727e458a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Daftar/SCN_001_TC_004_Daftar - Email Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>979cc74b-0e89-4e1d-a375-0544c78b1e72</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc1259ae-2d7a-4ade-a799-5a9bb1f75d38</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e950982c-d856-4f5a-ac81-81bf4af5ed82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc2fd174-0b73-4782-876d-dcd448143461</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85fa46cf-bb48-4132-bc13-3c14f9f5205e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>895c24ea-64d8-4829-a006-36bfdcb966c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83dee3f7-c647-4007-a741-77f621d60641</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1240e493-7f95-4fb3-88ee-36061bbd3da3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Daftar/SCN_001_TC_005_Daftar - Phone Number Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f01c517-e778-4d5a-b2fa-ef8e42e0720b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bb621d8-5885-48fc-a611-a7615b89d7e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5715304a-1c3c-4c71-b92e-682eda793d15</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>120199ae-fe34-4c2e-a0f1-3fce64fe83c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85ae613d-8642-421f-8fc2-4feb409daccf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba032fed-f99a-4db7-8f26-6bf87dec17e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a66c0c5-9ae1-43e9-9408-b65fe6348ee5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ea605781-8774-41de-8bf4-4e62ff7e835f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Daftar/SCN_001_TC_006_Daftar - Password Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b6394cc-54b2-47d0-9151-be598cfdbd27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54f6a10e-d09b-4b7b-be5d-21382fee5b7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5328bb69-a570-4491-9116-52421d3ebf54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>514a7fd3-7d0b-4cce-8895-24aa68aee521</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d998c064-32f7-4a55-9129-1eef370755b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6abf2e4-6039-4f6f-b6a0-61255bfa60a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>efc1c705-d42a-4715-9c96-f0203d830c1c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e169431a-6977-4719-9377-268a8abd0da8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Daftar/SCN_001_TC_007_Daftar - Confirm Password Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78bdba1b-d685-4236-8644-2fbb0fa18484</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a57dbf0-35ad-41a6-8ff8-af2a402d1e8a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b40d7c8f-9abf-4357-90e3-c91fffdd66a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58cc552a-1bd2-4cae-a027-d2b0453b68b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99ac0d36-8041-4570-8383-3a4ac7875d38</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2679fc38-9994-480b-8a15-0839792803c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f29232d-0955-4bf7-883d-3ec3c6bd6919</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>09e96c29-0bd6-474b-89c0-be06170897d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Daftar/SCN_001_TC_008_Daftar - Uncheck I am 18 year or Older</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03bf4b00-4148-4825-b351-84da3c483d42</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82382e9b-829c-4531-b2db-489a70023c70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3df4afa3-dd75-4360-bf26-55056aeea8db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c74bb0a-7eed-4c48-acde-4562e1e0e32b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ba03517-3da5-4151-af6a-c7c5b7031442</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bace9432-8595-4383-bbf8-8871ca8ad890</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b7c7e44-ec68-4471-8f0a-a474c2f0baaf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2d5f9a43-49f6-4e75-86bf-843d5f8361f6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Daftar/SCN_001_TC_009_Daftar - Phone Number Kurang dari 10 Digit</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af1472ca-635e-409f-bd27-a72917dbb2fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9170fb2f-8a17-44ae-801c-101a1933b692</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77b76d2a-213a-4937-8fd4-0190e49017fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8d5e8d4-dd6a-4d49-8c1d-03f7d21cb57c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77e2fd58-1041-41a8-81ff-a1a0a01ec969</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35102d1d-0ed0-4bc1-becc-d2a6d417ff95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d51a12d-d90e-4ee3-af41-1829d19d7771</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9f2d6ce2-177b-491d-a21c-051e01c85224</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Daftar/SCN_001_TC_010_Daftar - Phone Number Lebih dari 10 Digit</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9bae6a0-3b44-4ecf-ab5c-2d18bd8fc90a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d09f78ea-e51f-4b6c-b0d7-7bc3364342ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6a8daa7-0440-46b9-81c6-4170a7a68861</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b308d61a-e45b-4000-81ef-d3cfae80e6b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef7052e8-3ecf-44d8-a30e-527009cf293e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>372c69bb-faa0-4f76-acbf-f5142501313f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af8264e5-7a54-4ab3-baa6-b3c55092a017</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b062b9af-8d1b-4a9a-9cee-b4458410ae88</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Daftar/SCN_001_TC_011_Daftar - Format Email Salah</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f26a63eb-51bc-4055-9737-0911487a904b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>926d4509-0083-480a-8ae2-805e372f2d03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d987acf4-37ca-4d35-b7bd-a8bcd8c63462</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>417e7716-d0a3-477c-8dbc-8105310fb59a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b81ccb15-979e-4604-bdf6-17db4ef2b3a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47839d97-9c67-409e-af1c-38bde30ed7ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0914913-28d5-452d-8824-9e791d451981</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c3e61e9b-056a-4df1-9973-c5f32502355d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Daftar/SCN_001_TC_012_Daftar - Password dan Confirm Password Berbeda</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da3fc76a-98ea-4234-b8d5-29170d7c86c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d3c5e0a-8d8a-4e5e-a8bf-b7fc5abdb215</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ba180370-403c-417d-8cad-8732a0c363ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>261e84d9-6662-464b-a213-75fc97788a1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f37f450-46f5-43ea-ace6-3a29800b8fb2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9513b1b9-cc9d-4308-8fc4-25919a23cb22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bee60a7-e193-4a42-b33c-959a2598831b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
