<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Radio Button Male</name>
   <tag></tag>
   <elementGuidId>50ef2a7b-8c6a-4d1a-9554-f5c17f206f35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Male']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.mt-3.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c26c040-202d-47dc-ab98-03a93178e2f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>c4f41467-155e-4a22-a055-c9221113f0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Male</value>
      <webElementGuid>57977c48-d37a-45b3-bfd1-2fc6b27e6b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>gender</value>
      <webElementGuid>fadaa928-4397-442f-88b6-454fa25f8ec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-3 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>3e02d40d-675c-4f72-bbd2-f3a80f7e5cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-register[1]/div[@class=&quot;banner&quot;]/section[2]/div[@class=&quot;login-section-wrapper&quot;]/div[@class=&quot;login-wrapper my-auto p-5&quot;]/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;row mb-2&quot;]/div[@class=&quot;form-group col-md-6&quot;]/label[2]/input[@class=&quot;mt-3 ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>d778ab4c-aebf-4174-a338-eed16306f5b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Male']</value>
      <webElementGuid>d88d771a-7c1f-4204-a76e-daacad1619f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/input</value>
      <webElementGuid>94c3b358-9e55-492d-b581-44a59bbb7f29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio']</value>
      <webElementGuid>693db050-b983-4ff5-8868-3a0c530f5add</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
