<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign Up</name>
   <tag></tag>
   <elementGuidId>11c0a1c9-84ae-4423-9053-d65f6c917a07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#u_5_n_1O</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='u_5_n_1O']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5cc68dc9-6d26-4f33-ac23-87d9241b8626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>22b7ff82-035d-4034-a632-6578c0f8c939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_6j mvm _6wk _6wl _58mi _3ma _6o _6v</value>
      <webElementGuid>0baa8b53-582f-4758-af02-0ba9b70ba903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>websubmit</value>
      <webElementGuid>3fea6e76-6f63-40bf-b750-3e427db0614f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_5_n_1O</value>
      <webElementGuid>bbfdf1fa-0183-4008-bbe8-66cb13ba0378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign Up</value>
      <webElementGuid>e284f818-2953-48ac-89f1-7dccc72a94d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_5_n_1O&quot;)</value>
      <webElementGuid>79aa7c54-f211-4ebe-bb60-c7c833879b5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='u_5_n_1O']</value>
      <webElementGuid>1b37d001-6b2d-46ce-8587-bb26ccbf10d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reg_form_box']/div[11]/button</value>
      <webElementGuid>ce6cb826-c4e0-4b8d-a6fd-c5496758651e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookies Policy'])[1]/following::button[1]</value>
      <webElementGuid>f9e86000-0914-4e5c-bbed-5f5895f69576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[2]/following::button[1]</value>
      <webElementGuid>355beed9-60cb-4747-b339-ec3495a82e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Security check'])[1]/preceding::button[1]</value>
      <webElementGuid>7d35c8b0-a1cf-4b15-bed3-dff87df43ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required.'])[1]/preceding::button[1]</value>
      <webElementGuid>c0102802-f753-4681-8a0c-ad94047ef762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/button</value>
      <webElementGuid>c9628456-4efd-4b79-acd3-f59994fc8ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'websubmit' and @id = 'u_5_n_1O' and (text() = 'Sign Up' or . = 'Sign Up')]</value>
      <webElementGuid>3bbfe29e-c14a-400e-8563-256fa95c98ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
