<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_123456789101112131415161718192021222_566da4</name>
   <tag></tag>
   <elementGuidId>abc7bf53-3baf-4f41-9f7e-2aa4a4540dd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#day</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='day']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>437474ab-4eca-4058-82a1-a6f75b97dece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Day</value>
      <webElementGuid>a81f22e5-dc0d-408a-9b82-2a80dfd62884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>birthday_day</value>
      <webElementGuid>979caa09-21ad-4563-bd8c-ff195d7cf12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>day</value>
      <webElementGuid>678ff7c3-73d8-46b8-a81f-a27f9931827a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Day</value>
      <webElementGuid>ec83807b-0f1a-475e-8bed-e1ff1f70307a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_9407 _5dba _9hk6 _8esg</value>
      <webElementGuid>93037c0e-db20-44ca-9337-593fef07d47a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12345678910111213141516171819202122232425262728293031</value>
      <webElementGuid>d464f4f1-d85e-4e75-8a79-cdbb2c6b8dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;day&quot;)</value>
      <webElementGuid>e4c556fb-9c62-4de7-8397-e1515a52d55e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='day']</value>
      <webElementGuid>f56954f1-5f08-486c-8fe7-103e60cac26d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='u_5_i_Y/']/span/select</value>
      <webElementGuid>f308ee47-8f63-41df-ac47-43a8eb46d9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of birth'])[1]/following::select[1]</value>
      <webElementGuid>dbe6f7d6-5daa-4974-bb48-51c8c51f39e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('We couldn', &quot;'&quot;, 't create your accountWe were not able to sign you up for Facebook.')])[1]/following::select[1]</value>
      <webElementGuid>68fe6a61-2ac0-41bd-abef-43bc13249ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Age'])[1]/preceding::select[3]</value>
      <webElementGuid>5ce0e5dd-00d0-434c-b343-cd7b24da85ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/preceding::select[3]</value>
      <webElementGuid>874727e2-80e1-4440-bed5-3a2a100b2834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>cb9d52e8-8aa1-47d4-8a30-80cafb984190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'birthday_day' and @id = 'day' and @title = 'Day' and (text() = '12345678910111213141516171819202122232425262728293031' or . = '12345678910111213141516171819202122232425262728293031')]</value>
      <webElementGuid>0d21d70f-2de5-44c5-9700-e9e95e69d937</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
