<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SCN_002_Login - Data Tidak Valid</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>9cdd9b02-41a6-4cff-838d-2c73c4976b5e</testSuiteGuid>
   <testCaseLink>
      <guid>c323d448-0786-447c-ae05-e179fadabf8a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/SCN_002_TC_002_Login - data tidak valid</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8436a639-35ba-41c5-b3f6-1a01eea85b2b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestDataLoginDataTidakValid</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>8436a639-35ba-41c5-b3f6-1a01eea85b2b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email</value>
         <variableId>c776c9a3-5bce-40d9-90b0-7a4cd28fc0b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8436a639-35ba-41c5-b3f6-1a01eea85b2b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>0d0a8797-acce-436f-9506-e2f102940250</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8626d6a1-08f5-404a-abdf-ed7881405b22</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d68cafa8-5d5e-45d2-9321-215cf6d2f102</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/SCN_002_TC_003_Login - Email Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90b2c273-524f-4a08-8f70-95673cd5e330</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40a6e139-8e77-49cb-ac4e-dbc5c1e7f30e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f3cf7fe-c786-4070-8b3c-3b06e337b32e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>624483ce-c9ee-40bc-9a5b-be79c4295d8d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e3e837b0-9909-4d39-b593-b2940b924905</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/SCN_002_TC_004_Login - Password Kosong</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd2fbd67-7aec-4f92-ae42-c92a104f36ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a32a4c23-6fce-4e21-949a-41fb84b3c5b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7a55126-cbf2-4879-8bd6-7e0e4c7ca26a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>270b509a-3da2-4e46-bccf-9e61e4cd80d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b6df0ab1-fb98-4b19-ae9a-8420bf0ff9b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/SCN_002_TC_005_Login - Format Email Salah</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94373784-ce02-4a5b-b3bd-a3fe9f293f0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9dcac38e-632f-4311-8450-5d578f3202e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>25ee937a-d3dc-4bde-ae7c-84cb7d371a7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1ab297a3-b821-441d-8047-2538f07e793b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f74087c-08d6-451c-a536-948550381781</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>84072126-3bf7-4200-8445-909b205c852f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/SCN_002_TC_006_Login - Password Kurang dari 10 Character</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41d91dd2-798f-4fd2-908e-ff2134a6488b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0970ab1e-3707-421a-9172-2c9e57c534eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e1dc808-4164-427b-9210-50abeaeb70f7</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
